services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    depends_on:
      - prestart
    ports:
      - "8000:8000"
    volumes:
      - .:/application

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prestart:
    build:
      context: .
    depends_on:
      - postgres-db
    command: bash scripts/prestart.sh

volumes:
  postgres_data:

